name: GitHub Actions Demo
on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env:
        branch_name: main
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: get pr number
        run: echo "${{ github.event.pull_request.number }}"
             echo "${{ github.event.number }}"
             echo github.event.number = ${{ github.event.number  }}
             echo github.event.pull_request.number = ${{ github.event.pull_request.number }}
             echo github.event.issue.number = ${{ github.event.issue.number }}
      - name: test branch 
        run: export TAG=${branch_name}-dev-latest
             echo "${TAG}"
             docker pull hello-world &&
             docker tag hello-world localhost:5000/hello-world:${TAG} &&
             docker push localhost:5000/hello-world:${TAG}
             
